# Generated by Django 2.2.28 on 2024-03-09 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pub_review', '0002_pub_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='Postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='Pub_Name',
            new_name='pubName',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='Street_Name',
            new_name='streetName',
        ),
        migrations.RenameField(
            model_name='pub',
            old_name='UserID',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='pub',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pubProfile_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='userProfile_images'),
        ),
    ]
