# Generated by Django 2.2.28 on 2024-03-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0006_auto_20240310_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pub',
            old_name='userID',
            new_name='owner',
        ),
    ]
