# Generated by Django 2.2.28 on 2024-03-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0010_auto_20240311_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pubProfile_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='userProfile_images'),
        ),
    ]
