# Generated by Django 2.2.28 on 2024-03-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0012_favoritepubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepubs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pub_review.UserProfile'),
        ),
    ]
