# Generated by Django 2.2.28 on 2024-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0014_auto_20240312_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
