# Generated by Django 2.2.28 on 2024-03-11 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pub_review', '0015_auto_20240312_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='voter',
            field=models.ManyToManyField(related_name='voter_pub', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pub',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_pub', to=settings.AUTH_USER_MODEL),
        ),
    ]
