# Generated by Django 2.2.28 on 2024-03-12 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0016_auto_20240312_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pub_review.Pub'),
        ),
        migrations.AddField(
            model_name='question',
            name='pub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pub_review.Pub'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='userProfile_images/default-profile.png', null=True, upload_to='userProfile_images'),
        ),
    ]
