# Generated by Django 2.2.28 on 2024-03-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0019_auto_20240314_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
