# Generated by Django 2.2.28 on 2024-03-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0020_auto_20240314_1524'),
        ('pub_review', '0020_auto_20240318_0230'),
    ]

    operations = [
    ]
