# Generated by Django 2.2.28 on 2024-03-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub_review', '0020_auto_20240314_2223'),
        ('pub_review', '0021_merge_20240319_1629'),
    ]

    operations = [
    ]
